[package]
name = "featherbox"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "fbox"
path = "src/main.rs"

[dependencies]
anyhow = "1.0.98"
clap = { version = "4.5", features = ["derive"] }
duckdb = "1.1.3"
sea-orm = { version = "1.1.14", features = [ "sqlx-sqlite", "runtime-tokio-rustls", "macros" ] }
sqlparser = "0.58.0"
tokio = { version = "1", features = ["full"] }
yaml-rust2 = "0.10.3"

[dev-dependencies]
tempfile = "3.8"
