services:
  catalog_db_mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: testpass
      MYSQL_DATABASE: featherbox_test
      MYSQL_USER: featherbox
      MYSQL_PASSWORD: testpass
    command: --default-authentication-plugin=mysql_native_password
    entrypoint: >
      sh -c "
        docker-entrypoint.sh mysqld &
        until mysqladmin ping -h 127.0.0.1 --silent; do sleep 1; done
        mysql -u root -ptestpass -e \"GRANT ALL PRIVILEGES ON *.* TO 'featherbox'@'%';\"
        wait
      "
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    volumes:
      - catalog_mysql_data:/var/lib/mysql

  catalog_db_postgres:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: testpass
      POSTGRES_DB: featherbox_test
      POSTGRES_USER: featherbox
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U featherbox"]
      timeout: 20s
      retries: 10
    volumes:
      - catalog_postgres_data:/var/lib/postgresql/data

  datasource_mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: datasourcepass
      MYSQL_DATABASE: datasource_test
      MYSQL_USER: datasource
      MYSQL_PASSWORD: datasourcepass
    command: --default-authentication-plugin=mysql_native_password
    entrypoint: >
      sh -c "
        docker-entrypoint.sh mysqld &
        until mysqladmin ping -h 127.0.0.1 --silent; do sleep 1; done
        mysql -u root -pdatasourcepass -e \"GRANT ALL PRIVILEGES ON *.* TO 'datasource'@'%';\"
        wait
      "
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    volumes:
      - datasource_mysql_data:/var/lib/mysql

volumes:
  catalog_mysql_data:
  catalog_postgres_data:
  datasource_mysql_data:
