version: '3'

tasks:
  lint:
    desc: Run linter for Rust and pnpm, auto-fix where possible
    cmds:
      - nix develop --command cargo fix --allow-dirty --allow-staged
      - nix develop --command cargo clippy --fix --allow-dirty --allow-staged
      - cd src/ui && pnpm run check

  format:
    desc: Format Rust and UI code
    cmds:
      - nix develop --command cargo fmt
      - cd src/ui && pnpm run format

  test:
    desc: Run tests with proper environment setup
    cmds:
      - docker compose up -d
      - sleep 10
      - nix develop --command cargo test

  init:
    desc: Initialize direnv for nix development environment
    cmds:
      - echo 'use flake .' > .envrc
      - direnv allow

  dev:
    desc: Start development environment with test project
    cmds:
      - |
        cd /tmp
        PROJECT_NAME="test_$(date +%Y%m%d_%H%M%S)"
        echo "Creating test project: $PROJECT_NAME"
        cargo run --manifest-path {{.USER_WORKING_DIR}}/Cargo.toml -- new $PROJECT_NAME
        cd $PROJECT_NAME
        echo "Starting API server..."
        cargo run --manifest-path {{.USER_WORKING_DIR}}/Cargo.toml -- server &
        SERVER_PID=$!
        echo "Server started with PID: $SERVER_PID"
        sleep 3
        cd {{.USER_WORKING_DIR}}/src/ui
        echo "Starting Vite dev server..."
        pnpm run dev
