storage:
  type: local
  path: './storage'
database:
  type: sqlite
  path: './database.db'
connections:
  hello:
    type: mysql
    host: localhost
    port: 3306
    database: aa
    username: bb
    password: ${SECRET_HELLO_MYSQL_PASSWORD}
